### ISSUE TITLE
Add emailing feature to the Request Section

### ISSUE THREAD

**Issue by yashraj-02-techie** [GDSC-IIIT-Kalyani/PaperVault#3]
Checkout the request section. For now it has a node.js code that takes the input provided by the user and puts it into a file. Replace that logic and add a feature to send an email to the papervault id whenever a user submits a request. Email would be provided when you start working on the code.

**Comment by Ayush0922** [comment]
i can work on this , please assign me

**Comment by yashraj-02-techie** [comment]
You are assigned to the issue. You may start working on it

**Comment by Ayush0922** [comment]
> You are assigned to the issue. You may start working on it

cheers and thanks.

**Comment by yashraj-02-techie** [comment]
Completed by @Ayush0922 . 
When creating a PR please add closes #issue_number to close the issue.
